export const WORKS = [
  {
    type: "landing",
    array: [
      {
        src: "https://github.com/loki87by/how-to-learn",
        text: "firstProjectInfo",
        name: "howToLearn",
        animation: "standart",
        animationTime: "7s",
        type: "landingPage",
        stack: ["bem", "css", "html", "markdown"],
      },
      {
        src: "https://github.com/loki87by/russian-travel",
        text: "secondProjectInfo",
        name: "russianTravel",
        animation: "standart",
        animationTime: "11s",
        type: "landingPage",
        stack: ["bem", "css", "html", "markdown"],
      },
      {
        src: "https://github.com/loki87by/wildlife",
        text: "sevenProjectInfo",
        name: "wildlife",
        animation: "standart",
        animationTime: "3s",
        type: "landingPage",
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/ecwid-test",
        text: "ecwidProjectInfo",
        name: "ecwid",
        animation: "none" /*
        animationTime: "3s", */,
        type: "landingPage",
        aspectRatio: true,
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/ecwid-test-vue",
        text: "ecwidVueProjectInfo",
        name: "ecwidVue",
        animation: "none" /*
        animationTime: "3s", */,
        type: "landingPage",
        aspectRatio: true,
        stack: ["css", "html", "vue", "markdown"],
      },
    ],
  },
  {
    type: "webService",
    array: [
      {
        src: "https://github.com/loki87by/mesto",
        text: "thirdProjectInfo",
        name: "mesto",
        animation: "standart",
        animationTime: "3s",
        type: "webService",
        stack: ["bem", "css", "html", "js", "webpack", "markdown"],
      },
      {
        src: "https://github.com/loki87by/mesto-react",
        text: "fourthProjectInfo",
        name: "mestoReact",
        animation: "standart",
        animationTime: "4s",
        type: "webService",
        stack: ["bem", "css", "react", "markdown"],
      },
      {
        src: "https://github.com/loki87by/react-mesto-auth",
        text: "fifthProjectInfo",
        name: "reactMestoAuth",
        animation: "standart",
        animationTime: "3s",
        type: "webService",
        stack: ["bem", "css", "react", "markdown"],
      },
      {
        src: "https://github.com/loki87by/virtual-piano",
        text: "nineProjectInfo",
        name: "virtualPiano",
        animation: "none",
        type: "webService",
        aspectRatio: true,
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/photo-filter",
        text: "tenProjectInfo",
        name: "photoFilter",
        animation: "standart",
        animationTime: "2.5s",
        type: "webService",
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/gallery",
        text: "thirteenProjectInfo",
        name: "gallery",
        animation: "gallery",
        type: "webService",
        aspectRatio: true,
        stack: ["bem", "css", "react", "markdown"],
      },
      {
        src: "https://github.com/loki87by/gallery-angular",
        text: "forteenProjectInfo",
        name: "galleryAngular",
        animation: "galleryNg",
        /* animationTime: "2.5s", */
        type: "webService",
        aspectRatio: true,
        stack: ["angular", "css", "typescript", "markdown"],
      },
      {
        src: "https://github.com/loki87by/multidirection-slider",
        text: "multiRockSliderInfo",
        name: "multiRockSlider",
        animation: "multiRockSlider",
        /* animationTime: "2.5s", */
        type: "webService",
        aspectRatio: true,
        stack: ["js", "css", "html", "markdown"],
      },
      {
        src: "https://github.com/loki87by/JS-Clock",
        text: "jsClockInfo",
        name: "jsClock",
        animation: "jsClock",
        /* animationTime: "2.5s", */
        type: "webService",
        aspectRatio: true,
        stack: ["js", "css", "html", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/news-explorer-frontend",
        text: "diplomInfo",
        name: "newsExplorerApi",
        animation: "diplom",
        firstLinkText: "front",
        secondLinkText: "back",
        secondLink: "https://github.com/loki87by/news-explorer-api",
        type: "webService",
        type2: "server",
        stack: ["react", "css", "bem", "markdown"],
      },
    ],
  },
  {
    type: "server",
    array: [
      {
        src: "https://github.com/loki87by/express-mesto",
        text: "sixthProjectInfo",
        name: "expressMesto",
        animation: "standart",
        animationTime: "4s",
        type: "server",
        stack: ["mongo", "node", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/news-explorer-api",
        text: "diplomInfo",
        name: "newsExplorerApi",
        animation: "diplom",
        firstLinkText: "back",
        secondLinkText: "front",
        secondLink: "https://github.com/loki87by/news-explorer-frontend",
        type: "server",
        type2: "searchSystem",
        stack: ["mongo", "node", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/async-race-api",
        text: "asyncRaceInfo",
        name: "asyncRace",
        animation: "asyncRace",
        firstLinkText: "back",
        secondLinkText: "front",
        secondLink: "https://github.com/loki87by/async-race",
        type: "server",
        type2: "webGame",
        aspectRatio: true,
        stack: ["node", "markdown"],
      },
    ],
  },
  {
    type: "corporateWebsite",
    array: [
      {
        src: "https://github.com/loki87by/online-zoo",
        text: "eightProjectInfo",
        name: "onlineZoo",
        animation: "zoo",
        type: "corporateWebsite",
        stack: ["css", "html", "js", "svg", "markdown"],
      },
    ],
  },
  {
    type: "webGame",
    array: [
      {
        src: "https://github.com/loki87by/match-match-game",
        text: "elevenProjectInfo",
        name: "matchMatchGame",
        animation: "mmg",
        type: "webGame",
        aspectRatio: true,
        stack: ["css", "html", "js", "typescript", "webpack", "markdown"],
      },
      {
        src: "https://github.com/loki87by/2048game",
        text: "sixteenProjectInfo",
        name: "2048game",
        animation: "2048",
        type: "webGame",
        aspectRatio: true,
        stack: ["css", "react", "bem", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/async-race",
        text: "asyncRaceInfo",
        name: "asyncRace",
        animation: "asyncRace",
        firstLinkText: "front",
        secondLinkText: "back",
        secondLink: "https://github.com/loki87by/async-race-api",
        type: "webGame",
        type2: "server",
        aspectRatio: true,
        stack: [
          "css",
          "html",
          "js",
          "typescript",
          "webpack",
          "svg",
          "markdown",
        ],
      },
    ],
  },
  {
    type: "cleanWork",
    array: [
      {
        src: "https://github.com/loki87by/clean-code-s1e1",
        text: "twelveProjectInfo",
        name: "cleanCode",
        animation: "none",
        type: "cleanWork",
        stack: ["bem", "css", "html", "js", "markdown"],
      },
    ],
  },
  {
    type: "widget",
    array: [
      {
        src: "https://github.com/loki87by/my-weather-widget",
        text: "fifteenProjectInfo",
        name: "myWeatherWidget",
        animation: "none",
        type: "widget",
        additionally: true,
        stack: ["css", "react", "typescript", "webpack", "markdown"],
      },
    ],
  },
];
