export const WORKS = [
      {
        src: "https://github.com/loki87by/how-to-learn",
        text: "firstProjectInfo",
        name: "howToLearn",
        animation: "none",
        animationTime: "7s",
        type: ["landingPage", "simplest"],
        stack: ["bem", "css", "html", "markdown"],
      },
      {
        src: "https://github.com/loki87by/russian-travel",
        text: "secondProjectInfo",
        name: "russianTravel",
        animation: "none",
        animationTime: "11s",
        type: ["landingPage", "simplest"],
        stack: ["bem", "css", "html", "markdown"],
      },
      {
        src: "https://github.com/loki87by/wildlife",
        text: "sevenProjectInfo",
        name: "wildlife",
        animation: "none",
        animationTime: "3s",
        type: ["landingPage", "simplest"],
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/ecwid-test",
        text: "ecwidProjectInfo",
        name: "ecwid",
        animation: "none",
        type: ["landingPage", "webStore"],
        aspectRatio: true,
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/ecwid-test-vue",
        text: "ecwidVueProjectInfo",
        name: "ecwidVue",
        animation: "none",
        type: ["landingPage", "webStore"],
        aspectRatio: true,
        stack: ["css", "html", "vue", "markdown"],
      },
      {
        src: "https://github.com/loki87by/louvre",
        text: "louvreInfo",
        name: "louvre",
        animation: "none",
        animationTime: "6s",
        type: ["landingPage", "company"],
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/mesto",
        text: "thirdProjectInfo",
        name: "mesto",
        animation: "none",
        animationTime: "3s",
        type: ["social"],
        stack: ["bem", "css", "html", "js", "webpack", "markdown"],
      },
      {
        src: "https://github.com/loki87by/mesto-react",
        text: "fourthProjectInfo",
        name: "mestoReact",
        animation: "none",
        animationTime: "4s",
        type: ["social"],
        stack: ["bem", "css", "react", "markdown"],
      },
      {
        src: "https://github.com/loki87by/react-mesto-auth",
        text: "fifthProjectInfo",
        name: "reactMestoAuth",
        animation: "none",
        animationTime: "3s",
        type: ["social"],
        stack: ["bem", "css", "react", "markdown"],
      },
      {
        src: "https://github.com/loki87by/virtual-piano",
        text: "nineProjectInfo",
        name: "virtualPiano",
        animation: "none",
        type: ["webService", "sound"],
        aspectRatio: true,
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/photo-filter",
        text: "tenProjectInfo",
        name: "photoFilter",
        animation: "none",
        animationTime: "2.5s",
        type: ["webService", "pics"],
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/gallery",
        text: "thirteenProjectInfo",
        name: "gallery",
        animation: "gallery",
        type: ["webService", "pics"],
        aspectRatio: true,
        stack: ["bem", "css", "react", "markdown"],
      },
      {
        src: "https://github.com/loki87by/gallery-angular",
        text: "forteenProjectInfo",
        name: "galleryAngular",
        animation: "galleryNg",
        type: ["webService", "pics"],
        aspectRatio: true,
        stack: ["angular", "css", "typescript", "markdown"],
      },
      {
        src: "https://github.com/loki87by/multidirection-slider",
        text: "multiRockSliderInfo",
        name: "multiRockSlider",
        animation: "multiRockSlider",
        type: ["webService", "other"],
        aspectRatio: true,
        stack: ["js", "css", "html", "markdown"],
      },
      {
        src: "https://github.com/loki87by/JS-Clock",
        text: "jsClockInfo",
        name: "jsClock",
        animation: "jsClock",
        type: ["webService", "other"],
        aspectRatio: true,
        stack: ["js", "css", "html", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/news-explorer-frontend",
        text: "diplomInfo",
        name: "newsExplorerApi",
        animation: "diplom",
        firstLinkText: "front",
        secondLinkText: "back",
        secondLink: "https://github.com/loki87by/news-explorer-api",
        type: ["webService", "searchSystem"],
        stack: ["react", "css", "bem", "markdown"],
      },
      {
        double: true,
        src: "https://shpargaliki.ru",
        text: "shpargalikiInfo",
        name: "shpargaliki",
        animation: "shpargaliki",
        firstLinkText: "front",
        secondLinkText: "back",
        secondLink: "https://shpargaliki.ru",
        aspectRatio: true,
        type: ["webService", "webStore"],
        stack: ["html", "css", "js"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/contact-list",
        text: "contactListInfo",
        name: "contactList",
        animation: "contactList",
        firstLinkText: "front",
        aspectRatio: true,
        secondLinkText: "back",
        secondLink: "https://github.com/loki87by/contact-list-api",
        type: ["social"],
        stack: [
          "react",
          "css",
          "typescript",
          "redux",
          "bem",
          "webpack",
          "markdown",
        ],
      },
      {
        src: "https://github.com/loki87by/pseudo-social-network",
        text: "pseudoSocialNetworkInfo",
        name: "pseudoSocialNetwork",
        animation: "pseudoSocialNetwork",
        firstLinkText: "front",
        aspectRatio: true,
        type: ["social"],
        stack: ["react", "css", "typescript", "redux", "webpack", "markdown"],
      },
      {
        src: "https://github.com/loki87by/counters",
        text: "countersInfo",
        name: "counters",
        animation: "counters",
        firstLinkText: "front",
        aspectRatio: true,
        type: ["webService", "other"],
        stack: ["react", "css", "typescript", "redux", "webpack", "markdown"],
      },
      {
        src: "https://github.com/loki87by/disney-fairy-tales",
        text: "disneyInfo",
        name: "dft",
        animation: "disney",
        aspectRatio: true,
        type: ["webService", "other"],
        stack: ["react", "css", "bem", "markdown"],
      },
      {
        src: "https://github.com/loki87by/currency-converter",
        text: "currenciesInfo",
        name: "currencies",
        animation: "currencies",
        aspectRatio: true,
        type: ["webService", "other"],
        stack: ["react", "angular", "vue", "js", "css", "html", "markdown"],
      },
      {
        src: "https://github.com/loki87by/banki-shop",
        text: "bShopInfo",
        name: "bShop",
        animation: "bShop",
        aspectRatio: true,
        type: ["webService", "webStore"],
        stack: ["vue", "js", "css", "html", "bem", "markdown"],
      },
      {
        src: "https://github.com/loki87by/express-mesto",
        text: "sixthProjectInfo",
        name: "expressMesto",
        animation: "standart",
        animationTime: "4s",
        type: ["server"],
        stack: ["mongo", "node", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/news-explorer-api",
        text: "diplomInfo",
        name: "newsExplorerApi",
        animation: "diplom",
        firstLinkText: "back",
        secondLinkText: "front",
        secondLink: "https://github.com/loki87by/news-explorer-frontend",
        type: ["server"],
        stack: ["mongo", "node", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/async-race-api",
        text: "asyncRaceInfo",
        name: "asyncRace",
        animation: "asyncRace",
        firstLinkText: "back",
        secondLinkText: "front",
        aspectRatio: true,
        secondLink: "https://github.com/loki87by/async-race",
        type: ["server"],
        stack: ["node", "markdown"],
      },
      {
        double: true,
        src: "https://shpargaliki.ru",
        text: "shpargalikiApiInfo",
        name: "shpargaliki",
        animation: "shpargaliki",
        firstLinkText: "back",
        secondLinkText: "front",
        secondLink: "https://shpargaliki.ru",
        type: ["server"],
        stack: ["mongo", "node"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/contact-list-api",
        text: "contactListInfo",
        name: "contactList",
        animation: "contactList",
        firstLinkText: "back",
        aspectRatio: true,
        secondLinkText: "front",
        secondLink: "https://github.com/loki87by/contact-list",
        type: ["server"],
        stack: ["node", "markdown"],
      },
      {
        src: "https://github.com/loki87by/online-zoo",
        text: "eightProjectInfo",
        name: "onlineZoo",
        animation: "zoo",
        type: ["other", "corporateWebsite"],
        stack: ["css", "html", "js", "svg", "markdown"],
      },
      {
        src: "https://github.com/loki87by/match-match-game",
        text: "elevenProjectInfo",
        name: "matchMatchGame",
        animation: "mmg",
        type: ["webGame", "brouserGame"],
        aspectRatio: true,
        stack: ["css", "html", "js", "typescript", "webpack", "markdown"],
      },
      {
        src: "https://github.com/loki87by/2048game",
        text: "sixteenProjectInfo",
        name: "2048game",
        animation: "2048",
        type: ["webGame", "brouserGame"],
        aspectRatio: true,
        stack: ["css", "react", "bem", "markdown"],
      },
      {
        double: true,
        src: "https://github.com/loki87by/async-race",
        text: "asyncRaceInfo",
        name: "asyncRace",
        animation: "asyncRace",
        firstLinkText: "front",
        secondLinkText: "back",
        secondLink: "https://github.com/loki87by/async-race-api",
        type: ["webGame", "brouserGame"],
        aspectRatio: true,
        stack: [
          "css",
          "html",
          "js",
          "typescript",
          "webpack",
          "svg",
          "markdown",
        ],
      },
      {
        src: "https://github.com/loki87by/whack-a-mole",
        text: "wackAMoleInfo",
        name: "wackAMole",
        animation: "wackAMole",
        type: ["webGame", "brouserGame"],
        aspectRatio: true,
        stack: ["css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/clean-code-s1e1",
        text: "twelveProjectInfo",
        name: "cleanCode",
        animation: "none",
        aspectRatio: true,
        type: ["other", "cleanWork"],
        stack: ["bem", "css", "html", "js", "markdown"],
      },
      {
        src: "https://github.com/loki87by/my-weather-widget",
        text: "fifteenProjectInfo",
        name: "myWeatherWidget",
        animation: "none",
        type: ["other", "widget"],
        additionally: true,
        aspectRatio: true,
        stack: ["css", "react", "typescript", "webpack", "markdown"],
      },
];
